-keep class org.webrtc.** { *; }
-keep class com.twilio.video.** { *; }
-keep class com.twilio.common.** { *; }
-keep class com.twilio.** { *; }
-dontwarn org.apache.http.**
-keepattributes InnerClasses
